### ISSUE TITLE
Coverage step typo

### ISSUE THREAD

**Issue by ajoga** [fmind/mlops-python-package#1]
https://github.com/fmind/mlops-python-package/blob/618b83a0f1d8f218d131a8f415e95a44929654af/tasks/check.py#L19-L21

Shouldn't this invoke `coverage`?

**Comment by fmind** [comment]
Hello @ajoga ,
This is not necessary, as the package includes https://pypi.org/project/pytest-cov/ to integrate coverage and pytest
